Repository Team-EnderIO/EnderIO, pull requests merged in 2022-08, with the labels that each got.

#74 Add missing copper alloy components
  src/main/resources/assets/enderio/textures/block/copper_alloy_block.png
  src/main/resources/assets/enderio/textures/item/copper_alloy_grinding_ball.png
  src/main/resources/assets/enderio/textures/item/copper_alloy_nugget.png
Labels: 1.19, Assets

#75 1.19.2.
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Backend, 1.19

#73 Add Impulse Hopper
  src/api/java/com/enderio/api/capacitor/Scalers.java
  src/generated/resources/.cache/03e4de26f1265135874f8cdcaebc09d9c08eb42b
  src/generated/resources/.cache/67cce32b1c3cbbcb1f646605f4914e3f196986c2
  src/generated/resources/.cache/75bcd4dba6ca7d365462b0ec45e291d1056349c4
  src/generated/resources/.cache/7ffc26dd2bf9633e7fc00d0f64158c7250e050e7
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/.cache/eec194a88acc4b69ee022ff26153ceb1b8b9139a
  src/generated/resources/assets/enderio/blockstates/impulse_hopper.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/block/impulse_hopper.json
  src/generated/resources/assets/enderio/models/block/impulse_hopper_front_on.json
  src/generated/resources/assets/enderio/models/block/impulse_hopper_on.json
  src/generated/resources/assets/enderio/models/item/impulse_hopper.json
  src/generated/resources/data/enderio/loot_tables/blocks/impulse_hopper.json
  src/machines/java/com/enderio/machines/client/gui/screen/ImpulseHopperScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/ImpulseHopperBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/task/PoweredCraftingTask.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineCapacitorKeys.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/io/energy/IMachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/io/energy/ImmutableMachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/io/energy/MachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/menu/GhostMachineSlot.java
  src/machines/java/com/enderio/machines/common/menu/ImpulseHopperMenu.java
  src/main/resources/assets/enderio/models/block/impulse_hopper_front.json
  src/main/resources/assets/enderio/textures/block/impulse_hopper_front.png
  src/main/resources/assets/enderio/textures/block/impulse_hopper_front_on.png
Labels: Enhancement, 1.19

#77 Added nugget to ingot and ingot to block recipes for EIO materials
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/conductive_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/copper_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/dark_steel_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/end_steel_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/energetic_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/pulsating_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/redstone_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/soularium_nugget_to_ingot.json
  src/generated/resources/data/minecraft/advancements/recipes/enderio.main/vibrant_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/conductive_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/copper_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/dark_steel_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/end_steel_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/energetic_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/pulsating_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/redstone_alloy_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/soularium_nugget_to_ingot.json
  src/generated/resources/data/minecraft/recipes/vibrant_alloy_nugget_to_ingot.json
  src/main/java/com/enderio/base/data/recipe/MaterialRecipes.java
Labels: Enhancement, Needs Review, 1.19

#83 Stop! Jar time.
  build.gradle
  gradle.properties
Labels: Backend, 1.19

#71 Push comments from last meetup
  src/api/java/com/enderio/api/capability/ICapacitorData.java
  src/generated/resources/.cache/03e4de26f1265135874f8cdcaebc09d9c08eb42b
  src/generated/resources/.cache/67cce32b1c3cbbcb1f646605f4914e3f196986c2
  src/generated/resources/.cache/75bcd4dba6ca7d365462b0ec45e291d1056349c4
  src/generated/resources/.cache/7ffc26dd2bf9633e7fc00d0f64158c7250e050e7
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/.cache/eec194a88acc4b69ee022ff26153ceb1b8b9139a
  src/generated/resources/data/enderio/recipes/alloy_smelting/pulsating_alloy_ingot.json
  src/machines/java/com/enderio/machines/data/recipes/AlloyRecipeProvider.java
  src/main/java/com/enderio/base/common/capacitor/DefaultCapacitorData.java
  src/main/java/com/enderio/base/common/capacitor/LootCapacitorData.java
Labels: Documentation, 1.19
