Repository Team-EnderIO/EnderIO, pull requests merged in 2023-07, with the labels that each got.

#174 make itemstack capabilities
  .gitignore
  build.gradle
  src/api/java/com/enderio/api/capability/ICoordinateSelectionHolder.java
  src/api/java/com/enderio/api/capability/IToggled.java
  src/machines/java/com/enderio/machines/common/item/PoweredSpawnerItem.java
  src/machines/java/com/enderio/machines/common/recipe/AlloySmeltingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/SoulBindingRecipe.java
  src/main/java/com/enderio/base/common/capability/CoordinateSelectionHolder.java
  src/main/java/com/enderio/base/common/capability/EnergyStorageItemStack.java
  src/main/java/com/enderio/base/common/capability/EntityStorageItemStack.java
  src/main/java/com/enderio/base/common/capability/Toggled.java
  src/main/java/com/enderio/base/common/item/misc/BrokenSpawnerItem.java
  src/main/java/com/enderio/base/common/item/misc/LocationPrintoutItem.java
  src/main/java/com/enderio/base/common/item/tool/PoweredToggledItem.java
  src/main/java/com/enderio/base/common/item/tool/SoulVialItem.java
  src/main/java/com/enderio/base/common/recipe/ShapedEntityStorageRecipe.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, Backend, 1.20.1

#175 Fix capture of misc entity categories
  src/main/java/com/enderio/base/common/item/tool/SoulVialItem.java
  src/main/java/com/enderio/base/common/util/EntityCaptureUtils.java
Labels: Bug, 1.20.1

#186 remove hidden items from search
  src/decor/java/com/enderio/decoration/common/init/DecorBlocks.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
Labels: Bug, 1.20.1

#185 Small conduit fix
  src/conduits/java/com/enderio/conduits/common/blocks/ConduitBlock.java
Labels: Bug, 1.20.1

#187 JEI Transfer Handlers
  src/machines/java/com/enderio/machines/EIOMachines.java
  src/machines/java/com/enderio/machines/common/init/MachinePackets.java
  src/machines/java/com/enderio/machines/common/integrations/jei/MachinesJEI.java
  src/machines/java/com/enderio/machines/common/integrations/jei/transfer/CrafterRecipeTransferHandler.java
  src/machines/java/com/enderio/machines/common/io/item/MachineInventoryLayout.java
  src/machines/java/com/enderio/machines/common/menu/AlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/menu/CrafterMenu.java
  src/machines/java/com/enderio/machines/common/menu/EnchanterMenu.java
  src/machines/java/com/enderio/machines/common/menu/PrimitiveAlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/menu/SagMillMenu.java
  src/machines/java/com/enderio/machines/common/menu/SlicerMenu.java
  src/machines/java/com/enderio/machines/common/menu/SoulBinderMenu.java
  src/machines/java/com/enderio/machines/common/network/UpdateCrafterTemplatePacket.java
Labels: Enhancement, 1.20.1

#173 Modular machine blockentity
  src/api/java/com/enderio/api/capacitor/FixedScalable.java
  src/api/java/com/enderio/api/capacitor/LinearScalable.java
  src/api/java/com/enderio/api/capacitor/QuadraticScalable.java
  src/core/java/com/enderio/core/common/blockentity/EnderBlockEntity.java
  src/machines/java/com/enderio/machines/client/gui/screen/AlloySmelterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PaintingMachineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PoweredSpawnerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PrimitiveAlloySmelterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SagMillScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SlicerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulBinderScreen.java
  src/machines/java/com/enderio/machines/common/block/MachineBlock.java
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/CrafterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/CreativePowerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/EnchanterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/ImpulseHopperBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PaintingMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PoweredSpawnerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PrimitiveAlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SlicerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/StirlingGeneratorBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/VacuumChestBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPVacuumBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PowerGeneratingMachineEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredCraftingMachine.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredTaskMachineEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/VacuumMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/solar/SolarPanelBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/solar/SolarPanelTier.java
  src/machines/java/com/enderio/machines/common/blockentity/task/CraftingMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/IMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/IPoweredMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/PoweredCraftingMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/PoweredCraftingTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/PoweredTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/SpawnerMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/host/CraftingMachineTaskHost.java
  src/machines/java/com/enderio/machines/common/blockentity/task/host/MachineTaskHost.java
  src/machines/java/com/enderio/machines/common/blockentity/task/host/package-info.java
  src/machines/java/com/enderio/machines/common/config/client/MachinesClientConfig.java
  src/machines/java/com/enderio/machines/common/config/common/EnergyConfig.java
  src/machines/java/com/enderio/machines/common/config/common/MachinesCommonConfig.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/menu/PrimitiveAlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/network/PoweredSpawnerSoulPacket.java
  src/machines/java/com/enderio/machines/common/recipe/PaintingRecipe.java
  src/machines/java/com/enderio/machines/common/souldata/SpawnerSoul.java
  src/machines/java/com/enderio/machines/data/souldata/SoulDataProvider.java
Labels: Backend, 1.20.1

#193 Fix multiplayer data sync
  src/core/java/com/enderio/core/common/blockentity/EnderBlockEntity.java
  src/core/java/com/enderio/core/common/menu/SyncedMenu.java
  src/core/java/com/enderio/core/common/sync/EnderDataSlot.java
Labels: Bug, Backend, 1.20.1

#203 Fix grindstone and also mixin refmaps lmao
  build.gradle
  src/core/java/com/enderio/core/mixin/client/package-info.java
  src/main/java/com/enderio/base/mixin/ItemStackMixin.java
  src/main/resources/mixins.enderio.json
  src/main/resources/mixins.enderio.refmap.json
Labels: Bug, Backend, 1.20.1

#209 Fix painting machine
  src/machines/java/com/enderio/machines/common/recipe/PaintingRecipe.java
Labels: Bug, 1.20.1

#210 Remove unfinished tools and create armory module
  build.gradle
  src/armory/java/com/enderio/armory/EIOArmory.java
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/dark_steel_axe.json
  src/generated/resources/assets/enderio/models/item/dark_steel_pickaxe.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_blank.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_direct.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_1.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_2.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_3.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_empowered_4.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_fork.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_penetration_1.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_penetration_2.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_spoon.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_tnt.json
  src/generated/resources/assets/enderio/models/item/dark_steel_upgrade_tnt1.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_direct.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_empowered_1.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_empowered_2.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_empowered_3.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_empowered_4.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_fork.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_penetration_1.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_penetration_2.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_spoon.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_tnt.json
  src/generated/resources/data/enderio/advancements/recipes/misc/dark_steel_upgrade_tnt1.json
  src/generated/resources/data/enderio/advancements/recipes/tools/dark_steel_axe.json
  src/generated/resources/data/enderio/advancements/recipes/tools/dark_steel_pickaxe.json
  src/generated/resources/data/enderio/recipes/alloy_smelting/dark_steel_upgrade_blank.json
  src/generated/resources/data/enderio/recipes/dark_steel_axe.json
  src/generated/resources/data/enderio/recipes/dark_steel_pickaxe.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_direct.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_1.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_2.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_3.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_empowered_4.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_fork.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_penetration_1.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_penetration_2.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_spoon.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_tnt.json
  src/generated/resources/data/enderio/recipes/dark_steel_upgrade_tnt1.json
  src/machines/java/com/enderio/machines/data/recipes/AlloyRecipeProvider.java
  src/main/java/com/enderio/base/client/ClientSetup.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/data/recipe/ItemRecipes.java
Labels: Backend, 1.20.1

#214 Revert #193
  src/core/java/com/enderio/core/common/blockentity/EnderBlockEntity.java
  src/core/java/com/enderio/core/common/menu/SyncedMenu.java
  src/core/java/com/enderio/core/common/sync/EnderDataSlot.java
Labels: Bug, 1.20.1

#220 Added lapis recipes
  src/generated/resources/data/enderio/recipes/sagmilling/lapis.json
  src/generated/resources/data/enderio/recipes/sagmilling/lapis_block.json
  src/machines/java/com/enderio/machines/data/recipes/SagMillRecipeProvider.java
Labels: Enhancement, 1.20.1

#231 Try fix capacitor bank advancement order
  src/generated/resources/data/enderio/advancements/place_capacitor_bank.json
  src/machines/java/com/enderio/machines/data/advancements/MachinesAdvancementGenerator.java
Labels: 1.20.1

#229 Fix Fluid Tank Tooltip
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
Labels: Bug, 1.20.1

#232 Fix IGrindingBallData Reobf Issue
  src/api/java/com/enderio/api/grindingball/IGrindingBallData.java
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/main/java/com/enderio/base/common/recipe/GrindingBallRecipe.java
  src/main/java/com/enderio/base/common/util/GrindingBallManager.java
Labels: Bug, 1.20.1

#230 Add grinding JEI and coal recipe
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/main/java/com/enderio/base/common/handler/GrindingHandler.java
  src/main/java/com/enderio/base/common/integrations/jei/EnderIOJEI.java
  src/main/java/com/enderio/base/common/integrations/jei/EnderIOJEIRecipes.java
  src/main/java/com/enderio/base/common/integrations/jei/category/GrindingCategory.java
  src/main/java/com/enderio/base/common/integrations/jei/helper/FakeGrindingRecipe.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
  src/main/java/com/enderio/base/mixin/ItemStackMixin.java
Labels: 1.20.1

#248 Fix sugar cane and plant pot sag recipes
  src/generated/resources/data/enderio/recipes/sagmilling/flower_pot.json
  src/generated/resources/data/enderio/recipes/sagmilling/sugar_canes.json
  src/machines/java/com/enderio/machines/data/recipes/SagMillRecipeProvider.java
Labels: Bug, 1.20.1

#266 Remove graves and unfired urn
  src/generated/resources/assets/enderio/blockstates/grave.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/unfired_death_urn.json
  src/generated/resources/data/enderio/advancements/recipes/misc/unfired_death_urn.json
  src/generated/resources/data/enderio/recipes/unfired_death_urn.json
  src/main/java/com/enderio/base/client/renderer/blockentity/GraveRenderer.java
  src/main/java/com/enderio/base/client/renderer/blockentity/package-info.java
  src/main/java/com/enderio/base/common/block/GraveBlock.java
  src/main/java/com/enderio/base/common/blockentity/GraveBlockEntity.java
  src/main/java/com/enderio/base/common/blockentity/GraveHandler.java
  src/main/java/com/enderio/base/common/config/common/BaseCommonConfig.java
  src/main/java/com/enderio/base/common/config/common/GraveConfig.java
  src/main/java/com/enderio/base/common/init/EIOBlockEntities.java
  src/main/java/com/enderio/base/common/init/EIOBlocks.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/data/recipe/MaterialRecipes.java
  src/main/resources/assets/enderio/models/block/grave.json
  src/main/resources/assets/enderio/textures/item/unfired_death_urn.png
Labels: MC-1.20.1

#268 fix xp
  src/conduits/java/com/enderio/conduits/common/types/FluidConduitTicker.java
  src/machines/java/com/enderio/machines/common/blockentity/XPVacuumBlockEntity.java
Labels: Type-Bug, MC-1.20.1

#263 Added changelog tracking
  CHANGELOG.md
  build.gradle
Labels: Type-RFC, MC-1.20.1

#262 Fixed some alloy smelter related bugs
  CHANGELOG.md
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PrimitiveAlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/task/CraftingMachineTask.java
Labels: Type-Bug, MC-1.20.1

#271 multismelting
  CHANGELOG.md
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/integrations/vanilla/VanillaAlloySmeltingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/AlloySmeltingRecipe.java
Labels: Type-Feature, MC-1.20.1

#280 Change/conduit pickup
  CHANGELOG.md
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitBlockEntity.java
  src/conduits/java/com/enderio/conduits/common/blocks/ConduitBlock.java
  src/core/java/com/enderio/core/common/util/PlayerInteractionUtil.java
Labels: Type-Feature, MC-1.20.1, Area-Conduits

#269 Fix conduit shape and connector type
  CHANGELOG.md
  src/conduits/java/com/enderio/conduits/common/ConduitShape.java
Labels: Type-Bug, Area-Conduits

#275 IOConfig fixes
  CHANGELOG.md
  src/machines/java/com/enderio/machines/client/gui/widget/ioconfig/IOConfigButton.java
  src/machines/java/com/enderio/machines/client/gui/widget/ioconfig/IOConfigWidget.java
Labels: Type-Bug, MC-1.20.1

#282 Updated contributing guidelines
  .github/pull_request_template.md
  README.md
Labels: Type-Documentation, Area-Backend

#281 Lower forge to 47.0.42
  CHANGELOG.md
  gradle.properties
Labels: Area-Backend, MC-1.20.1

#277 Update grinding handler to use in-world crafting for grindstone or obsidian
  CHANGELOG.md
  src/main/java/com/enderio/base/common/handler/GrindingHandler.java
Labels: Type-Bug, Type-Feature, MC-1.20.1, P-0-High

#288 Added new grains and powdered coal to JEI
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/main/java/com/enderio/base/common/integrations/jei/EnderIOJEI.java
  src/main/java/com/enderio/base/common/integrations/jei/category/GrindingCategory.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: Type-Documentation, MC-1.20.1

#267 Changed the redstone control symbols for the 1.12 ones
  src/api/java/com/enderio/api/misc/RedstoneControl.java
  src/api/resources/assets/enderio/textures/gui/icons/redstone_control.png
Labels: MC-1.20.1

#290 Added recipes to upgrade and craft capacitor banks.
  src/generated/resources/data/enderio/advancements/recipes/misc/advanced_capacitor_bank.json
  src/generated/resources/data/enderio/advancements/recipes/misc/advanced_capacitor_bank_upgrade.json
  src/generated/resources/data/enderio/advancements/recipes/misc/basic_capacitor_bank.json
  src/generated/resources/data/enderio/advancements/recipes/misc/vibrant_capacitor_bank.json
  src/generated/resources/data/enderio/advancements/recipes/misc/vibrant_capacitor_bank_upgrade.json
  src/generated/resources/data/enderio/recipes/advanced_capacitor_bank.json
  src/generated/resources/data/enderio/recipes/advanced_capacitor_bank_upgrade.json
  src/generated/resources/data/enderio/recipes/basic_capacitor_bank.json
  src/generated/resources/data/enderio/recipes/vibrant_capacitor_bank.json
  src/generated/resources/data/enderio/recipes/vibrant_capacitor_bank_upgrade.json
  src/machines/java/com/enderio/machines/data/recipes/MachineRecipeProvider.java
Labels: Type-Feature, MC-1.20.1

#286 Fix SoulBinder tooltip
  CHANGELOG.md
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceWidget.java
Labels: Type-Bug, MC-1.20.1

#295 add insets to ioconfig
  src/machines/java/com/enderio/machines/client/gui/widget/ioconfig/IOConfigButton.java
Labels: Type-Feature, Area-Backend, MC-1.20.1

#289 Fix Stirling Generator for real this time
  src/machines/java/com/enderio/machines/common/blockentity/StirlingGeneratorBlockEntity.java
Labels: Type-Bug, MC-1.20.1

#322 Remove Serialization from MultiCapabilityProvider
  src/api/java/com/enderio/api/capability/MultiCapabilityProvider.java
  src/machines/java/com/enderio/machines/common/item/PoweredSpawnerItem.java
  src/main/java/com/enderio/base/common/item/capacitors/FixedCapacitorItem.java
  src/main/java/com/enderio/base/common/item/capacitors/LootCapacitorItem.java
  src/main/java/com/enderio/base/common/item/darksteel/IDarkSteelItem.java
  src/main/java/com/enderio/base/common/item/misc/BrokenSpawnerItem.java
  src/main/java/com/enderio/base/common/item/misc/LocationPrintoutItem.java
  src/main/java/com/enderio/base/common/item/tool/ColdFireIgniter.java
  src/main/java/com/enderio/base/common/item/tool/LevitationStaffItem.java
  src/main/java/com/enderio/base/common/item/tool/PoweredToggledItem.java
  src/main/java/com/enderio/base/common/item/tool/SoulVialItem.java
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#320 Replace missed NBTKeys + Add paint to paint recipe
  src/generated/resources/data/enderio/loot_tables/blocks/painted_crafting_table.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_fence.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_fence_gate.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_glowstone.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_redstone_block.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_sand.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_slab.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_stairs.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_trapdoor.json
  src/generated/resources/data/enderio/loot_tables/blocks/painted_wooden_pressure_plate.json
  src/generated/resources/data/enderio/recipes/painting/painted_crafting_table_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_fence_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_fence_gate_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_glowstone_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_redstone_block_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_sand_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_slab_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_stairs_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_trapdoor_frompainted.json
  src/generated/resources/data/enderio/recipes/painting/painted_wooden_pressure_plate_frompainted.json
  src/machines/java/com/enderio/machines/data/recipes/PaintingRecipeProvider.java
  src/main/java/com/enderio/base/client/renderer/PaintedBlockColor.java
  src/main/java/com/enderio/base/common/block/painted/PaintedFenceBlock.java
  src/main/java/com/enderio/base/common/entity/PaintedSandEntity.java
  src/main/java/com/enderio/base/data/loot/DecorLootTable.java
Labels: Type-Bug, Type-Feature, MC-1.20.1, P-1-Medium

#287 Change/add conduit tooltips
  CHANGELOG.md
  src/conduits/java/com/enderio/conduits/common/types/ItemClientConduitData.java
  src/core/java/com/enderio/core/client/gui/widgets/CheckBox.java
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: Type-Bug, MC-1.20.1, Area-Conduits

#324 allows rightclicking machines with capacitors to autoequip
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineBlockEntity.java
  src/main/java/com/enderio/base/common/blockentity/IMachineInstall.java
  src/main/java/com/enderio/base/common/item/capacitors/BaseCapacitorItem.java
  src/main/java/com/enderio/base/common/item/capacitors/FixedCapacitorItem.java
  src/main/java/com/enderio/base/common/item/capacitors/LootCapacitorItem.java
Labels: Type-Feature, MC-1.20.1

#296 Conduit Cleaning
  src/api/java/com/enderio/api/conduit/IClientConduitData.java
  src/api/java/com/enderio/api/conduit/IConduitType.java
  src/api/java/com/enderio/api/conduit/NodeIdentifier.java
  src/api/java/com/enderio/api/conduit/TieredConduit.java
  src/api/java/com/enderio/api/conduit/ticker/CapabilityAwareConduitTicker.java
  src/api/java/com/enderio/api/conduit/ticker/IConduitTicker.java
  src/api/java/com/enderio/api/conduit/ticker/IIOAwareConduitTicker.java
  src/api/java/com/enderio/api/conduit/ticker/ILoadedAwareConduitTicker.java
  src/conduits/java/com/enderio/conduits/ConduitNBTKeys.java
  src/conduits/java/com/enderio/conduits/EIOConduits.java
  src/conduits/java/com/enderio/conduits/client/gui/ConduitScreen.java
  src/conduits/java/com/enderio/conduits/client/model/ConduitBlockModel.java
  src/conduits/java/com/enderio/conduits/common/ConduitShape.java
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitBlockEntity.java
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitBundle.java
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitConnection.java
  src/conduits/java/com/enderio/conduits/common/blockentity/OffsetHelper.java
  src/conduits/java/com/enderio/conduits/common/blockentity/connection/DynamicConnectionState.java
  src/conduits/java/com/enderio/conduits/common/blocks/ConduitBlock.java
  src/conduits/java/com/enderio/conduits/common/init/ConduitLang.java
  src/conduits/java/com/enderio/conduits/common/init/EnderConduitTypes.java
  src/conduits/java/com/enderio/conduits/common/integrations/ae2/AE2ConduitType.java
  src/conduits/java/com/enderio/conduits/common/items/ConduitBlockItem.java
  src/conduits/java/com/enderio/conduits/common/menu/ConduitMenu.java
  src/conduits/java/com/enderio/conduits/common/network/ConduitSavedData.java
  src/conduits/java/com/enderio/conduits/common/types/EnergyConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/FluidClientData.java
  src/conduits/java/com/enderio/conduits/common/types/FluidConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/ItemClientConduitData.java
  src/conduits/java/com/enderio/conduits/common/types/ItemConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/RedstoneConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/RedstoneConduitType.java
  src/conduits/java/com/enderio/conduits/common/types/RedstoneExtendedData.java
  src/conduits/java/com/enderio/conduits/common/types/SimpleConduitType.java
  src/conduits/java/com/enderio/conduits/data/ConduitTagProvider.java
  src/conduits/resources/assets/enderio/textures/gui/conduit_icon.png
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/data/enderio/tags/blocks/redstone_connectable.json
Labels: Type-Bug, MC-1.20.1, Area-Conduits, P-0-High

#317 Add painter recipe, ender resonator and enderman skull
  src/generated/resources/assets/enderio/blockstates/enderman_head.json
  src/generated/resources/assets/enderio/blockstates/wall_enderman_head.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/enderman_head.json
  src/generated/resources/data/enderio/advancements/recipes/misc/painting_machine.json
  src/generated/resources/data/enderio/loot_tables/blocks/enderman_head.json
  src/generated/resources/data/enderio/recipes/painting_machine.json
  src/generated/resources/data/enderio/recipes/slicing/ender_resonator.json
  src/machines/java/com/enderio/machines/data/recipes/MachineRecipeProvider.java
  src/machines/java/com/enderio/machines/data/recipes/SlicingRecipeProvider.java
  src/main/java/com/enderio/base/client/ClientSetup.java
  src/main/java/com/enderio/base/client/renderer/block/EnderSkullRenderer.java
  src/main/java/com/enderio/base/client/renderer/item/EnderSkullIBEWLR.java
  src/main/java/com/enderio/base/common/block/EnderSkullBlock.java
  src/main/java/com/enderio/base/common/block/WallEnderSkullBlock.java
  src/main/java/com/enderio/base/common/blockentity/EnderSkullBlockEntity.java
  src/main/java/com/enderio/base/common/init/EIOBlockEntities.java
  src/main/java/com/enderio/base/common/init/EIOBlocks.java
  src/main/java/com/enderio/base/common/item/darksteel/DarkSteelSwordItem.java
  src/main/java/com/enderio/base/common/item/misc/EnderSkullBlockItem.java
Labels: Type-Bug, Type-Feature, MC-1.20.1, Area-Parity

#335 Complete Stone to Sand line in Sagmill and Add powder to ingot recipe
  src/generated/resources/data/enderio/advancements/recipes/misc/copper_ingot_from_blasting.json
  src/generated/resources/data/enderio/advancements/recipes/misc/copper_ingot_from_smelting.json
  src/generated/resources/data/enderio/advancements/recipes/misc/gold_ingot_from_blasting.json
  src/generated/resources/data/enderio/advancements/recipes/misc/gold_ingot_from_smelting.json
  src/generated/resources/data/enderio/advancements/recipes/misc/iron_ingot_from_blasting.json
  src/generated/resources/data/enderio/advancements/recipes/misc/iron_ingot_from_smelting.json
  src/generated/resources/data/enderio/recipes/copper_ingot_from_blasting.json
  src/generated/resources/data/enderio/recipes/copper_ingot_from_smelting.json
  src/generated/resources/data/enderio/recipes/gold_ingot_from_blasting.json
  src/generated/resources/data/enderio/recipes/gold_ingot_from_smelting.json
  src/generated/resources/data/enderio/recipes/iron_ingot_from_blasting.json
  src/generated/resources/data/enderio/recipes/iron_ingot_from_smelting.json
  src/generated/resources/data/enderio/recipes/sagmilling/copper_ore.json
  src/generated/resources/data/enderio/recipes/sagmilling/gravel.json
  src/generated/resources/data/enderio/recipes/sagmilling/stone.json
  src/machines/java/com/enderio/machines/data/recipes/SagMillRecipeProvider.java
  src/main/java/com/enderio/base/data/recipe/MaterialRecipes.java
Labels: Type-Feature, MC-1.20.1

#297 Machine (Mainly Alloy Smelter) Fixes
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PaintingMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PrimitiveAlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SlicerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/integrations/jei/MachineJEIRecipes.java
  src/machines/java/com/enderio/machines/common/integrations/jei/MachinesJEI.java
  src/machines/java/com/enderio/machines/common/menu/MachineMenu.java
  src/machines/java/com/enderio/machines/common/menu/MachineSlot.java
  src/machines/java/com/enderio/machines/common/menu/PrimitiveAlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/recipe/AlloySmeltingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/PaintingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/RecipeCaches.java
  src/machines/java/com/enderio/machines/common/recipe/SagMillingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/SlicingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/SoulBindingRecipe.java
  src/machines/java/com/enderio/machines/common/utility/RecipeInputCache.java
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#172 Added the wired charger
  CHANGELOG.md
  src/core/java/com/enderio/core/common/menu/SyncedMenu.java
  src/generated/resources/assets/enderio/blockstates/wired_charger.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/block/wired_charger.json
  src/generated/resources/assets/enderio/models/block/wired_charger_front_on.json
  src/generated/resources/assets/enderio/models/block/wired_charger_on.json
  src/generated/resources/assets/enderio/models/item/wired_charger.json
  src/generated/resources/data/enderio/advancements/recipes/misc/wired_charger.json
  src/generated/resources/data/enderio/loot_tables/blocks/wired_charger.json
  src/generated/resources/data/enderio/recipes/wired_charger.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/machines/java/com/enderio/machines/client/gui/screen/WiredChargerScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/WiredChargerBlockEntity.java
  src/machines/java/com/enderio/machines/common/config/common/EnergyConfig.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/menu/WiredChargerMenu.java
  src/machines/java/com/enderio/machines/data/recipes/MachineRecipeProvider.java
  src/main/resources/assets/enderio/models/block/wired_charger_front.json
  src/main/resources/assets/enderio/textures/block/wired_charger_front.png
Labels: Type-Feature, MC-1.20.1, Area-Parity

#341 Misc bugs
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/recipe/RecipeCaches.java
  src/machines/java/com/enderio/machines/common/utility/RecipeInputCache.java
  src/main/java/com/enderio/base/mixin/ItemStackMixin.java
  src/main/resources/mixins.enderio.json
Labels: Type-Bug, MC-1.20.1, P-0-High

#355 ae2 undisabling a connection with a yeta wrench now properly reconnects
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitBlockEntity.java
  src/conduits/java/com/enderio/conduits/common/integrations/ae2/AE2ConduitType.java
Labels: MC-1.20.1, Area-Conduits, P-2-Low

#348 Reduce lang duplication by reusing glass names
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/main/java/com/enderio/base/common/block/glass/FusedQuartzBlock.java
  src/main/java/com/enderio/base/common/block/glass/GlassBlocks.java
  src/main/java/com/enderio/base/common/block/glass/GlassIdentifier.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: P-2-Low, Area-Lang

#365 Change autosmelt to GLM and use datagen.
  src/generated/resources/data/enderio/loot_modifiers/auto_smelt.json
  src/generated/resources/data/enderio/loot_modifiers/broken_spawner.json
  src/generated/resources/data/enderio/loot_modifiers/capacitor_loot.json
  src/generated/resources/data/enderio/loot_modifiers/direct_upgrade.json
  src/generated/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/main/java/com/enderio/EnderIO.java
  src/main/java/com/enderio/base/common/enchantment/AutoSmeltHandler.java
  src/main/java/com/enderio/base/common/enchantment/AutoSmeltModifier.java
  src/main/java/com/enderio/base/common/init/EIOLootModifiers.java
  src/main/java/com/enderio/base/common/item/darksteel/upgrades/direct/DirectUpgradeLootModifier.java
  src/main/java/com/enderio/base/common/loot/BrokenSpawnerLootModifier.java
  src/main/java/com/enderio/base/common/loot/CapacitorLootModifier.java
  src/main/java/com/enderio/base/data/loot/EIOLootModifiersProvider.java
  src/main/resources/data/enderio/loot_modifiers/broken_spawner.json
  src/main/resources/data/forge/loot_modifiers/global_loot_modifiers.json
Labels: Type-Bug, MC-1.20.1, Area-Conduits, P-1-Medium

#374 Fix sword model.
  src/generated/resources/assets/enderio/models/item/dark_steel_sword.json
  src/main/java/com/enderio/base/common/init/EIOItems.java
Labels: Type-Bug, MC-1.20.1

#339 Energy conduit round robin.
  src/conduits/java/com/enderio/conduits/common/init/EnderConduitTypes.java
  src/conduits/java/com/enderio/conduits/common/types/EnergyConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/EnergyExtendedData.java
  src/conduits/java/com/enderio/conduits/common/types/ItemConduitTicker.java
Labels: Type-Feature, MC-1.20.1, Area-Conduits

#393 Using GitHub actions for nightly and release
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/verify.yml
  CHANGELOG.md
  build.gradle
  gradle.properties
Labels: Area-Backend, P-0-High

#396 Check boss tag
  src/generated/resources/data/enderio/tags/entity_types/soul_vial_blacklist.json
  src/main/java/com/enderio/base/common/util/EntityCaptureUtils.java
  src/main/java/com/enderio/base/data/tags/EIOEntityTagsProvider.java
Labels: Type-Bug, MC-1.20.1

#399 Fix Enderman Head crash
  src/main/java/com/enderio/base/client/renderer/block/EnderSkullRenderer.java
  src/main/java/com/enderio/base/client/renderer/item/EnderSkullIBEWLR.java
  src/main/java/com/enderio/base/common/item/misc/EnderSkullBlockItem.java
  src/main/java/com/enderio/base/mixin/SkullBlockRendererMixin.java
  src/main/resources/mixins.enderio.json
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#400 Stop using datagen to make machine models
  src/generated/resources/assets/enderio/blockstates/primitive_alloy_smelter.json
  src/generated/resources/assets/enderio/models/block/pressurized_fluid_tank.json
  src/generated/resources/assets/enderio/models/block/primitive_alloy_smelter.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/data/model/MachineModelUtil.java
  src/machines/resources/assets/enderio/models/block/alloy_smelter.json
  src/machines/resources/assets/enderio/models/block/alloy_smelter_active.json
  src/machines/resources/assets/enderio/models/block/crafter.json
  src/machines/resources/assets/enderio/models/block/crafter_active.json
  src/machines/resources/assets/enderio/models/block/enchanter.json
  src/machines/resources/assets/enderio/models/block/impulse_hopper.json
  src/machines/resources/assets/enderio/models/block/impulse_hopper_active.json
  src/machines/resources/assets/enderio/models/block/painting_machine.json
  src/machines/resources/assets/enderio/models/block/painting_machine_active.json
  src/machines/resources/assets/enderio/models/block/powered_spawner.json
  src/machines/resources/assets/enderio/models/block/powered_spawner_active.json
  src/machines/resources/assets/enderio/models/block/powered_spawner_front_on.json
  src/machines/resources/assets/enderio/models/block/pressurized_fluid_tank_body.json
  src/machines/resources/assets/enderio/models/block/primitive_alloy_smelter.json
  src/machines/resources/assets/enderio/models/block/primitive_alloy_smelter_active.json
  src/machines/resources/assets/enderio/models/block/sag_mill.json
  src/machines/resources/assets/enderio/models/block/sag_mill_active.json
  src/machines/resources/assets/enderio/models/block/slice_and_splice.json
  src/machines/resources/assets/enderio/models/block/slice_and_splice_active.json
  src/machines/resources/assets/enderio/models/block/soul_binder.json
  src/machines/resources/assets/enderio/models/block/soul_binder_active.json
  src/machines/resources/assets/enderio/models/block/stirling_generator.json
  src/machines/resources/assets/enderio/models/block/stirling_generator_active.json
  src/machines/resources/assets/enderio/models/block/wired_charger.json
Labels: Area-Assets, MC-1.20.1

#377 Fix XP fluid conversions
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
Labels: Type-Bug, MC-1.20.1

#273 Loot Tweaks
  src/api/java/com/enderio/api/capacitor/CapacitorModifier.java
  src/generated/resources/data/enderio/loot_modifiers/alloy_loot.json
  src/generated/resources/data/enderio/loot_modifiers/capacitor_loot.json
  src/generated/resources/data/enderio/loot_modifiers/common_loot.json
  src/generated/resources/data/enderio/loot_tables/chests/alloy_loot.json
  src/generated/resources/data/enderio/loot_tables/chests/common_loot.json
  src/generated/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/main/java/com/enderio/EnderIO.java
  src/main/java/com/enderio/base/common/capacitor/CapacitorUtil.java
  src/main/java/com/enderio/base/common/capacitor/LootCapacitorData.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/common/init/EIOLootModifiers.java
  src/main/java/com/enderio/base/common/item/capacitors/LootCapacitorItem.java
  src/main/java/com/enderio/base/common/loot/CapacitorLootModifier.java
  src/main/java/com/enderio/base/common/loot/ChestLootModifier.java
  src/main/java/com/enderio/base/common/loot/SetLootCapacitorFunction.java
  src/main/java/com/enderio/base/data/loot/ChestLootProvider.java
  src/main/java/com/enderio/base/data/loot/EIOLootModifiersProvider.java
Labels: Type-Bug, Type-RFC, MC-1.20.1

#336 Consume inputs after processing
  src/machines/java/com/enderio/machines/common/blockentity/task/CraftingMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/host/CraftingMachineTaskHost.java
  src/machines/java/com/enderio/machines/common/blockentity/task/host/MachineTaskHost.java
  src/machines/java/com/enderio/machines/common/integrations/vanilla/VanillaAlloySmeltingRecipe.java
Labels: Type-Feature, Type-RFC, MC-1.20.1

#381 New Crowdin updates
  src/main/resources/assets/enderio/lang/en_gb.json
  src/main/resources/assets/enderio/lang/en_pt.json
  src/main/resources/assets/enderio/lang/fr_fr.json
  src/main/resources/assets/enderio/lang/lol_us.json
  src/main/resources/assets/enderio/lang/ru_ru.json
  src/main/resources/assets/enderio/lang/zh_cn.json
Labels: Area-Lang
