Repository Team-EnderIO/EnderIO, pull requests merged in 2023-10, with the labels that each got.

#481 Changes to drain behavior
  src/machines/java/com/enderio/machines/common/blockentity/DrainBlockEntity.java
Labels: Type-Enhancement, MC-1.20.1

#483 Add speed and power cap upgrades to the Soul Engine
  src/machines/java/com/enderio/machines/client/gui/screen/SoulEngineScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulEngineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/config/common/EnergyConfig.java
  src/machines/resources/assets/enderio/models/block/soul_engine_active.json
Labels: Type-Enhancement, MC-1.20.1

#535 Remove checkstyle from gradle
  build.gradle
Labels: Area-Backend

#476 Optimize shape calls
  src/conduits/java/com/enderio/conduits/common/ConduitShape.java
Labels: Area-Backend, MC-1.20.1, Area-Conduits

#496 Add XP Obelisk
  .editorconfig
  src/core/java/com/enderio/core/common/menu/SyncedMenu.java
  src/generated/resources/assets/enderio/blockstates/xp_obelisk.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/xp_obelisk.json
  src/generated/resources/data/enderio/advancements/recipes/misc/xp_obelisk.json
  src/generated/resources/data/enderio/loot_tables/blocks/xp_obelisk.json
  src/generated/resources/data/enderio/recipes/xp_obelisk.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/machines/java/com/enderio/machines/client/MachinesClientSetup.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulBinderScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/XPObeliskScreen.java
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceCraftingWidget.java
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceWidget.java
  src/machines/java/com/enderio/machines/client/rendering/blockentity/XPObeliskBER.java
  src/machines/java/com/enderio/machines/common/blockentity/XPObeliskBlockEntity.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/lang/MachineLang.java
  src/machines/java/com/enderio/machines/common/menu/XPObeliskMenu.java
  src/machines/java/com/enderio/machines/data/recipes/MachineRecipeProvider.java
  src/machines/resources/assets/enderio/models/block/xp_obelisk.json
  src/main/java/com/enderio/base/common/init/EIOFluids.java
  src/main/java/com/enderio/base/common/util/ExperienceUtil.java
  src/main/resources/assets/enderio/textures/gui/icons/xp_obelisk.png
  src/main/resources/assets/enderio/textures/gui/xp_obelisk.png
Labels: MC-1.20.1, Area-Parity

#484 Delay model update to stop flickering
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineBlockEntity.java
Labels: Type-Bug, MC-1.20.1, Area-Rendering
