Repository Team-EnderIO/EnderIO, pull requests merged in 2023-01, with the labels that each got.

#80 Add Vacuum Blocks
  src/core/java/com/enderio/core/client/RenderUtil.java
  src/core/java/com/enderio/core/client/gui/widgets/ToggleImageButton.java
  src/core/java/com/enderio/core/common/sync/BooleanDataSlot.java
  src/generated/resources/assets/enderio/blockstates/vacuum_chest.json
  src/generated/resources/assets/enderio/blockstates/xp_vacuum.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/vacuum_chest.json
  src/generated/resources/assets/enderio/models/item/xp_vacuum.json
  src/generated/resources/data/enderio/loot_tables/blocks/vacuum_chest.json
  src/generated/resources/data/enderio/loot_tables/blocks/xp_vacuum.json
  src/machines/java/com/enderio/machines/client/gui/screen/VacuumChestScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/XPVacuumScreen.java
  src/machines/java/com/enderio/machines/client/gui/widget/FluidStackStaticWidget.java
  src/machines/java/com/enderio/machines/common/blockentity/VacuumChestBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPVacuumBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/VacuumMachineEntity.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/menu/VacuumChestMenu.java
  src/machines/java/com/enderio/machines/common/menu/XPVacuumMenu.java
  src/main/java/com/enderio/EnderIO.java
  src/main/java/com/enderio/base/client/ClientSetup.java
  src/main/java/com/enderio/base/client/particle/RangeParticle.java
  src/main/java/com/enderio/base/common/config/common/BlocksConfig.java
  src/main/java/com/enderio/base/common/init/EIOParticles.java
  src/main/java/com/enderio/base/common/item/tool/ElectromagnetItem.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
  src/main/java/com/enderio/base/common/particle/RangeParticleData.java
  src/main/java/com/enderio/base/common/particle/RangeParticleType.java
  src/main/java/com/enderio/base/common/util/AttractionUtil.java
  src/main/resources/assets/enderio/models/block/hollow_core_frame.json
  src/main/resources/assets/enderio/models/block/vacuum_chest.json
  src/main/resources/assets/enderio/models/block/xp_vacuum.json
  src/main/resources/assets/enderio/particles/range_particle.json
  src/main/resources/assets/enderio/textures/block/hollow_core_frame.png
  src/main/resources/assets/enderio/textures/block/hollow_core_frame_inner.png
  src/main/resources/assets/enderio/textures/block/vacuum_portal.png
  src/main/resources/assets/enderio/textures/block/vacuum_portal.png.mcmeta
  src/main/resources/assets/enderio/textures/gui/icons/buttons.png
  src/main/resources/assets/enderio/textures/gui/icons/range_buttons.png
  src/main/resources/assets/enderio/textures/particle/white.png
Labels: Enhancement, Needs Review, 1.19

#101 Slot Access Feature Preview
  build.gradle
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/EnchanterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/ImpulseHopperBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SlicerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/StirlingGeneratorBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/task/PoweredCraftingTask.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/io/item/MachineInventoryLayout.java
  src/machines/java/com/enderio/machines/common/io/item/MultiSlotAccess.java
  src/machines/java/com/enderio/machines/common/io/item/SingleSlotAccess.java
  src/machines/java/com/enderio/machines/common/menu/AlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/menu/EnchanterMenu.java
  src/machines/java/com/enderio/machines/common/menu/FluidTankMenu.java
  src/machines/java/com/enderio/machines/common/menu/GhostMachineSlot.java
  src/machines/java/com/enderio/machines/common/menu/ImpulseHopperMenu.java
  src/machines/java/com/enderio/machines/common/menu/MachineSlot.java
  src/machines/java/com/enderio/machines/common/menu/PrimitiveAlloySmelterMenu.java
  src/machines/java/com/enderio/machines/common/menu/SagMillMenu.java
  src/machines/java/com/enderio/machines/common/menu/SlicerMenu.java
  src/machines/java/com/enderio/machines/common/menu/StirlingGeneratorMenu.java
  src/machines/java/com/enderio/machines/common/recipe/AlloySmeltingRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/EnchanterRecipe.java
  src/machines/java/com/enderio/machines/common/recipe/SagMillingRecipe.java
Labels: Needs Review, Backend, RFC, 1.19

#99 Add Crafter
  src/generated/resources/assets/enderio/blockstates/crafter.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/block/crafter.json
  src/generated/resources/assets/enderio/models/block/crafter_front_on.json
  src/generated/resources/assets/enderio/models/block/crafter_on.json
  src/generated/resources/assets/enderio/models/item/crafter.json
  src/generated/resources/data/enderio/loot_tables/blocks/crafter.json
  src/machines/java/com/enderio/machines/client/gui/screen/CrafterScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/CrafterBlockEntity.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/io/item/MachineInventoryLayout.java
  src/machines/java/com/enderio/machines/common/menu/CrafterMenu.java
  src/machines/java/com/enderio/machines/common/menu/GhostMachineSlot.java
  src/machines/java/com/enderio/machines/common/menu/PreviewMachineSlot.java
  src/machines/java/com/enderio/machines/data/model/MachineModelUtil.java
  src/main/resources/assets/enderio/models/block/crafter_frame.json
  src/main/resources/assets/enderio/models/block/crafter_front.json
  src/main/resources/assets/enderio/textures/block/crafter_front.png
  src/main/resources/assets/enderio/textures/block/crafter_front_on.png
  src/main/resources/assets/enderio/textures/block/crafter_front_on.png.mcmeta
  src/main/resources/assets/enderio/textures/block/crafter_side.png
  src/main/resources/assets/enderio/textures/block/crafter_top.png
Labels: Enhancement, Blocked, 1.19
