Repository Team-EnderIO/EnderIO, pull requests merged in 2023-06, with the labels that each got.

#121 Fluid tank branch (Third time's the charm??)
  src/core/java/com/enderio/core/common/util/PlayerInteractionUtil.java
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/block/fluid_tank.json
  src/generated/resources/assets/enderio/models/block/pressurized_fluid_tank.json
  src/machines/java/com/enderio/machines/client/gui/widget/FluidStackWidget.java
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/io/fluid/MachineFluidTank.java
  src/machines/java/com/enderio/machines/common/item/FluidTankItem.java
  src/machines/java/com/enderio/machines/common/recipe/SagMillingRecipe.java
  src/main/java/com/enderio/base/common/blockentity/IWrenchable.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: Enhancement, 1.19.4

#134 Fix staff of levity recipe
  src/generated/resources/data/enderio/recipes/staff_of_levity.json
  src/main/java/com/enderio/base/data/recipe/ItemRecipes.java
Labels: Bug, 1.20.1

#135 Make tank recipes use slot access
  src/machines/java/com/enderio/machines/common/recipe/TankRecipe.java
Labels: Backend, 1.20.1

#131 Remove energy transfer cap
  src/api/java/com/enderio/api/capacitor/CapacitorModifier.java
  src/api/java/com/enderio/api/conduit/IConduitMenuData.java
  src/api/java/com/enderio/api/conduit/PowerConduitType.java
  src/conduits/java/com/enderio/conduits/common/init/ConduitItems.java
  src/conduits/java/com/enderio/conduits/common/init/EnderConduitTypes.java
  src/conduits/java/com/enderio/conduits/common/types/EnergyConduitTicker.java
  src/conduits/java/com/enderio/conduits/common/types/FluidClientData.java
  src/conduits/java/com/enderio/conduits/common/types/FluidConduitType.java
  src/conduits/java/com/enderio/conduits/common/types/ItemClientConduitData.java
  src/conduits/java/com/enderio/conduits/data/recipe/ConduitRecipes.java
  src/conduits/resources/assets/enderio/textures/block/conduit/energy.png
  src/conduits/resources/assets/enderio/textures/block/conduit/power2.png
  src/conduits/resources/assets/enderio/textures/block/conduit/power3.png
  src/conduits/resources/assets/enderio/textures/gui/conduit_icon.png
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/energy_conduit.json
  src/generated/resources/assets/enderio/models/item/power1_conduit.json
  src/generated/resources/assets/enderio/models/item/power2_conduit.json
  src/generated/resources/data/enderio/advancements/recipes/building_blocks/energy_conduit.json
  src/generated/resources/data/enderio/recipes/energy_conduit.json
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/CrafterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/CreativePowerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/ImpulseHopperBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/PoweredSpawnerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SlicerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/StirlingGeneratorBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PowerGeneratingMachineEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredCraftingMachine.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredTaskMachineEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/sync/MachineEnergyDataSlot.java
  src/machines/java/com/enderio/machines/common/io/energy/IMachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/io/energy/ImmutableMachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/io/energy/MachineEnergyStorage.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: Needs Review, 1.20.1

#154 Removed iron alloy
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/iron_alloy_ingot.json
  src/generated/resources/assets/enderio/models/item/iron_alloy_nugget.json
  src/generated/resources/data/forge/tags/items/ingots/iron.json
  src/generated/resources/data/forge/tags/items/nuggets/iron.json
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/resources/assets/enderio/textures/item/iron_alloy_grinding_ball.png
  src/main/resources/assets/enderio/textures/item/iron_alloy_ingot.png
  src/main/resources/assets/enderio/textures/item/iron_alloy_nugget.png
Labels: 1.20.1

#171 Machine Energy Input Cap
  src/conduits/java/com/enderio/conduits/common/types/EnergyConduitTicker.java
  src/machines/java/com/enderio/machines/common/io/energy/MachineEnergyStorage.java
Labels: Backend, 1.20.1
