Repository Team-EnderIO/EnderIO, pull requests merged in 2023-11, with the labels that each got.

#531 Implement elevator behaviour for travel anchors
  src/machines/java/com/enderio/machines/client/MachinesClientEvents.java
  src/machines/java/com/enderio/machines/client/MachinesClientSetup.java
  src/machines/java/com/enderio/machines/client/rendering/travel/TravelAnchorHud.java
  src/machines/java/com/enderio/machines/common/block/TravelAnchorBlock.java
  src/main/java/com/enderio/base/client/renderer/travel/RenderTravelTargets.java
  src/main/java/com/enderio/base/common/handler/TravelHandler.java
  src/main/java/com/enderio/base/common/init/EIOPackets.java
  src/main/java/com/enderio/base/common/network/RequestTravelPacket.java
Labels: MC-1.20.1, Area-Parity

#363 Fix exp display for the SoulBinder
  src/machines/java/com/enderio/machines/client/gui/screen/SoulBinderScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/recipe/SoulBindingRecipe.java
Labels: Type-Bug, MC-1.20.1

#549 Adds overlay on top of Ghost and Preview Slots
  src/machines/java/com/enderio/machines/client/gui/screen/AlloySmelterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/CapacitorBankScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/CrafterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/DrainScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/EnchanterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/FluidTankScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/ImpulseHopperScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/MachineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PaintingMachineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PoweredSpawnerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PrimitiveAlloySmelterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SagMillScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SlicerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulBinderScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulEngineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/StirlingGeneratorScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/TravelAnchorScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/VacuumChestScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/WiredChargerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/XPObeliskScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/XPVacuumScreen.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Type-Enhancement, MC-1.20.1, Area-Rendering

#489 Fix resize bug with Enum Widgets
  src/core/java/com/enderio/core/client/gui/screen/EIOScreen.java
  src/core/java/com/enderio/core/client/gui/widgets/EnumIconWidget.java
Labels: Type-Bug, MC-1.20.1

#542 Feature/short travel staff teleport
  src/main/java/com/enderio/base/common/handler/TravelHandler.java
  src/main/java/com/enderio/base/common/item/tool/TravelStaffItem.java
Labels: Type-Enhancement, MC-1.20.1, Area-Parity

#547 Rework Experience Calculation logic
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceWidget.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPObeliskBlockEntity.java
  src/main/java/com/enderio/base/common/item/tool/ExperienceRodItem.java
  src/main/java/com/enderio/base/common/util/ExperienceUtil.java
Labels: Type-Bug, Area-Backend, MC-1.20.1, P-0-High

#479 Add Machine active tooltip
  src/core/java/com/enderio/core/common/network/slot/SetNetworkDataSlot.java
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/machines/java/com/enderio/machines/client/gui/screen/AlloySmelterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/CrafterScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/DrainScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/FluidTankScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/ImpulseHopperScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PaintingMachineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/PoweredSpawnerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SagMillScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SlicerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulBinderScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/SoulEngineScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/StirlingGeneratorScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/VacuumChestScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/WiredChargerScreen.java
  src/machines/java/com/enderio/machines/client/gui/screen/XPVacuumScreen.java
  src/machines/java/com/enderio/machines/client/gui/widget/ActiveWidget.java
  src/machines/java/com/enderio/machines/client/gui/widget/CapacitorEnergyWidget.java
  src/machines/java/com/enderio/machines/common/blockentity/AlloySmelterBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/DrainBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/MachineState.java
  src/machines/java/com/enderio/machines/common/blockentity/MachineStateType.java
  src/machines/java/com/enderio/machines/common/blockentity/PoweredSpawnerBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulEngineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/StirlingGeneratorBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPVacuumBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/PoweredMachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/task/CraftingMachineTask.java
  src/machines/java/com/enderio/machines/common/blockentity/task/SpawnerMachineTask.java
  src/machines/java/com/enderio/machines/common/io/energy/MachineEnergyStorage.java
  src/machines/java/com/enderio/machines/common/io/item/MachineInventory.java
  src/machines/java/com/enderio/machines/common/item/BoundSoulBlockItem.java
  src/machines/java/com/enderio/machines/common/lang/MachineLang.java
Labels: Type-Enhancement, MC-1.20.1
