Repository Team-EnderIO/EnderIO, pull requests merged in 2023-08, with the labels that each got.

#279 Add to Buffers to DataSlots
  src/conduits/java/com/enderio/conduits/common/blockentity/ConduitBundleNetworkDataSlot.java
  src/core/java/com/enderio/core/common/blockentity/EnderBlockEntity.java
  src/core/java/com/enderio/core/common/network/C2SDataSlotChange.java
  src/core/java/com/enderio/core/common/network/S2CDataSlotUpdate.java
  src/core/java/com/enderio/core/common/network/slot/BooleanNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/EnumNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/FloatNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/FluidStackNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/IntegerNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/ListNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/LongNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/NBTSerializableNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/NBTSerializingNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/NetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/ResourceLocationNetworkDataSlot.java
  src/machines/java/com/enderio/machines/common/blockentity/capacitorbank/CapacitorBankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/sync/LargeMachineEnergyDataSlot.java
  src/machines/java/com/enderio/machines/common/blockentity/sync/MachineEnergyNetworkDataSlot.java
Labels: Type-Feature, Area-Backend, MC-1.20.1

#414 Use Enchantment Descriptions.
  build.gradle
  gradle.properties
  src/core/java/com/enderio/core/common/util/TooltipUtil.java
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/data/enderio/recipes/enchanting/withering.json
  src/machines/java/com/enderio/machines/data/recipes/EnchanterRecipeProvider.java
  src/main/java/com/enderio/EnderIO.java
  src/main/java/com/enderio/base/client/tooltip/TooltipHandler.java
  src/main/java/com/enderio/base/common/enchantment/EIOEnchantmentCategories.java
  src/main/java/com/enderio/base/common/enchantment/WitherBladeEnchantment.java
  src/main/java/com/enderio/base/common/enchantment/WitherBoltEnchantment.java
  src/main/java/com/enderio/base/common/enchantment/WitherEnchantment.java
  src/main/java/com/enderio/base/common/init/EIOEnchantments.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
Labels: Type-Feature, Area-Mod Integration, MC-1.20.1, P-2-Low

#423 Raise forge version for compat with neo.
  gradle.properties
Labels: Area-Backend

#425 Fix IO Overlay not rendering
  src/core/java/com/enderio/core/common/network/slot/NBTSerializingNetworkDataSlot.java
  src/core/java/com/enderio/core/common/network/slot/NetworkDataSlot.java
  src/generated/resources/assets/enderio/blockstates/alloy_smelter.json
  src/generated/resources/assets/enderio/blockstates/crafter.json
  src/generated/resources/assets/enderio/blockstates/enchanter.json
  src/generated/resources/assets/enderio/blockstates/impulse_hopper.json
  src/generated/resources/assets/enderio/blockstates/painting_machine.json
  src/generated/resources/assets/enderio/blockstates/powered_spawner.json
  src/generated/resources/assets/enderio/blockstates/primitive_alloy_smelter.json
  src/generated/resources/assets/enderio/blockstates/sag_mill.json
  src/generated/resources/assets/enderio/blockstates/slice_and_splice.json
  src/generated/resources/assets/enderio/blockstates/soul_binder.json
  src/generated/resources/assets/enderio/blockstates/stirling_generator.json
  src/generated/resources/assets/enderio/blockstates/wired_charger.json
  src/generated/resources/assets/enderio/models/block/alloy_smelter_combined.json
  src/generated/resources/assets/enderio/models/block/crafter_combined.json
  src/generated/resources/assets/enderio/models/block/enchanter_combined.json
  src/generated/resources/assets/enderio/models/block/impulse_hopper_combined.json
  src/generated/resources/assets/enderio/models/block/painting_machine_combined.json
  src/generated/resources/assets/enderio/models/block/powered_spawner_combined.json
  src/generated/resources/assets/enderio/models/block/primitive_alloy_smelter_combined.json
  src/generated/resources/assets/enderio/models/block/sag_mill_combined.json
  src/generated/resources/assets/enderio/models/block/slice_and_splice_combined.json
  src/generated/resources/assets/enderio/models/block/soul_binder_combined.json
  src/generated/resources/assets/enderio/models/block/stirling_generator_combined.json
  src/generated/resources/assets/enderio/models/block/wired_charger_combined.json
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
  src/machines/java/com/enderio/machines/data/model/MachineModelUtil.java
  src/main/resources/assets/minecraft/atlases/blocks.json
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#439 You didn't see anything.
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
Labels: MC-1.20.1, P-0-High

#440 Fixed where all mobs that are not explicitly registered have dropped …
  src/main/java/com/enderio/base/common/item/darksteel/DarkSteelSwordItem.java
Labels: Type-Bug, MC-1.20.1

#103 Add Travel Anchor and Staff of Travelling
  src/api/java/com/enderio/api/integration/Integration.java
  src/api/java/com/enderio/api/integration/IntegrationManager.java
  src/api/java/com/enderio/api/travel/ITravelTarget.java
  src/api/java/com/enderio/api/travel/TravelEntry.java
  src/api/java/com/enderio/api/travel/TravelRegistry.java
  src/api/java/com/enderio/api/travel/TravelRenderer.java
  src/api/java/com/enderio/api/travel/package-info.java
  src/core/java/com/enderio/core/CoreNBTKeys.java
  src/core/java/com/enderio/core/common/network/slot/StringNetworkDataSlot.java
  src/generated/resources/assets/enderio/blockstates/travel_anchor.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/staff_of_travelling.json
  src/generated/resources/assets/enderio/models/item/travel_anchor.json
  src/generated/resources/data/enderio/loot_tables/blocks/travel_anchor.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/machines/java/com/enderio/machines/EIOMachines.java
  src/machines/java/com/enderio/machines/client/gui/screen/TravelAnchorScreen.java
  src/machines/java/com/enderio/machines/client/rendering/travel/OutlineBuffer.java
  src/machines/java/com/enderio/machines/client/rendering/travel/OutlineRenderType.java
  src/machines/java/com/enderio/machines/client/rendering/travel/TravelAnchorRenderer.java
  src/machines/java/com/enderio/machines/client/rendering/travel/package-info.java
  src/machines/java/com/enderio/machines/common/block/TravelAnchorBlock.java
  src/machines/java/com/enderio/machines/common/blockentity/TravelAnchorBlockEntity.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/integrations/EnderIOMachinesSelfIntegration.java
  src/machines/java/com/enderio/machines/common/menu/TravelAnchorMenu.java
  src/machines/java/com/enderio/machines/common/travel/AnchorTravelTarget.java
  src/machines/resources/assets/enderio/models/block/hollow_core_frame.json
  src/main/java/com/enderio/base/client/ClientSetup.java
  src/main/java/com/enderio/base/client/renderer/travel/RenderTravelTargets.java
  src/main/java/com/enderio/base/client/renderer/travel/TravelParticleHandler.java
  src/main/java/com/enderio/base/common/config/common/ItemsConfig.java
  src/main/java/com/enderio/base/common/handler/TravelHandler.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/common/item/darksteel/IDarkSteelItem.java
  src/main/java/com/enderio/base/common/item/darksteel/upgrades/EmpoweredUpgrade.java
  src/main/java/com/enderio/base/common/item/tool/TravelStaffItem.java
  src/main/java/com/enderio/base/common/lang/EIOLang.java
  src/main/java/com/enderio/base/common/travel/TravelSavedData.java
  src/main/java/com/enderio/base/common/travel/package-info.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/enderio/models/block/travel_anchor.json
  src/main/resources/assets/enderio/textures/block/ender_still.png
  src/main/resources/assets/enderio/textures/block/ender_still.png.mcmeta
  src/main/resources/assets/enderio/textures/gui/icons/visibility_buttons.png
  src/main/resources/assets/enderio/textures/gui/travel_accessible.png
  src/main/resources/assets/enderio/textures/gui/travel_anchor.png
  src/main/resources/assets/enderio/textures/item/staff_of_travelling.png
Labels: Type-Feature, MC-1.20.1

#452 Hotfix for travel renderer on server
  src/api/java/com/enderio/api/travel/TravelEntry.java
  src/api/java/com/enderio/api/travel/TravelRegistry.java
  src/machines/java/com/enderio/machines/EIOMachines.java
Labels: Type-Bug, MC-1.20.1, P-0-High

#473 Ignore sides when using experience rod.
  src/main/java/com/enderio/base/common/item/tool/ExperienceRodItem.java
Labels: Type-Feature, MC-1.20.1

#456 Anchor changes
  src/core/java/com/enderio/core/common/network/CoreNetwork.java
  src/machines/java/com/enderio/machines/EIOMachines.java
  src/machines/java/com/enderio/machines/client/rendering/travel/TravelAnchorRenderer.java
  src/machines/java/com/enderio/machines/common/block/TravelAnchorBlock.java
  src/machines/java/com/enderio/machines/common/blockentity/TravelAnchorBlockEntity.java
  src/machines/java/com/enderio/machines/common/init/MachinePackets.java
  src/machines/java/com/enderio/machines/common/network/MachineNetwork.java
  src/machines/java/com/enderio/machines/common/travel/AnchorTravelTarget.java
  src/main/java/com/enderio/base/common/init/EIOPackets.java
  src/main/java/com/enderio/base/common/network/AddTravelTargetPacket.java
  src/main/java/com/enderio/base/common/network/RemoveTravelTargetPacket.java
  src/main/java/com/enderio/base/common/network/SyncTravelDataPacket.java
  src/main/java/com/enderio/base/common/travel/TravelSavedData.java
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#373 Add Drain
  src/core/java/com/enderio/core/common/blockentity/EnderBlockEntity.java
  src/core/java/com/enderio/core/common/network/slot/NetworkDataSlot.java
  src/generated/resources/assets/enderio/blockstates/drain.json
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/block/drain_active_combined.json
  src/generated/resources/assets/enderio/models/block/drain_combined.json
  src/generated/resources/assets/enderio/models/item/drain.json
  src/generated/resources/data/enderio/advancements/recipes/misc/drain.json
  src/generated/resources/data/enderio/loot_tables/blocks/drain.json
  src/generated/resources/data/enderio/recipes/drain.json
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/generated/resources/data/minecraft/tags/blocks/needs_iron_tool.json
  src/machines/java/com/enderio/machines/client/gui/screen/DrainScreen.java
  src/machines/java/com/enderio/machines/common/blockentity/DrainBlockEntity.java
  src/machines/java/com/enderio/machines/common/config/client/MachinesClientBlocksConfig.java
  src/machines/java/com/enderio/machines/common/config/common/EnergyConfig.java
  src/machines/java/com/enderio/machines/common/init/MachineBlockEntities.java
  src/machines/java/com/enderio/machines/common/init/MachineBlocks.java
  src/machines/java/com/enderio/machines/common/init/MachineMenus.java
  src/machines/java/com/enderio/machines/common/menu/DrainMenu.java
  src/machines/java/com/enderio/machines/data/recipes/MachineRecipeProvider.java
  src/machines/resources/assets/enderio/models/block/drain.json
  src/machines/resources/assets/enderio/models/block/drain_active.json
  src/machines/resources/assets/enderio/textures/block/drain_front.png
  src/machines/resources/assets/enderio/textures/block/drain_front_active.png
  src/main/resources/assets/enderio/textures/gui/drain.png
Labels: Type-Feature, MC-1.20.1

#475 Add inv sorter support
  src/machines/java/com/enderio/machines/EIOMachines.java
  src/machines/java/com/enderio/machines/common/menu/EnchanterMenu.java
Labels: Type-Bug, Area-Mod Integration, MC-1.20.1, P-1-Medium

#478 Removed gear rotation
  src/generated/resources/assets/enderio/models/item/dark_bimetal_gear.json
  src/generated/resources/assets/enderio/models/item/dark_bimetal_gear_helper.json
  src/generated/resources/assets/enderio/models/item/energized_gear.json
  src/generated/resources/assets/enderio/models/item/energized_gear_helper.json
  src/generated/resources/assets/enderio/models/item/iron_gear.json
  src/generated/resources/assets/enderio/models/item/iron_gear_helper.json
  src/generated/resources/assets/enderio/models/item/stone_gear.json
  src/generated/resources/assets/enderio/models/item/stone_gear_helper.json
  src/generated/resources/assets/enderio/models/item/vibrant_gear.json
  src/generated/resources/assets/enderio/models/item/vibrant_gear_helper.json
  src/generated/resources/assets/enderio/models/item/wood_gear.json
  src/generated/resources/assets/enderio/models/item/wood_gear_helper.json
  src/main/java/com/enderio/base/client/ClientSetup.java
  src/main/java/com/enderio/base/client/renderer/item/IRotatingItem.java
  src/main/java/com/enderio/base/client/renderer/item/RotatingItemBEWLR.java
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/common/item/misc/GearItem.java
  src/main/java/com/enderio/base/data/model/item/RotatingItemModel.java
Labels: Area-Assets, MC-1.20.1, Area-Rendering
