Repository Team-EnderIO/EnderIO, pull requests merged in 2023-09, with the labels that each got.

#500 Added tags for crystals
  src/generated/resources/data/forge/tags/items/gems.json
  src/generated/resources/data/forge/tags/items/gems/ender_crystal.json
  src/generated/resources/data/forge/tags/items/gems/enticing_crystal.json
  src/generated/resources/data/forge/tags/items/gems/prescient_crystal.json
  src/generated/resources/data/forge/tags/items/gems/pulsating_crystal.json
  src/generated/resources/data/forge/tags/items/gems/vibrant_crystal.json
  src/generated/resources/data/forge/tags/items/gems/weather_crystal.json
  src/main/java/com/enderio/base/common/init/EIOItems.java
  src/main/java/com/enderio/base/common/tag/EIOTags.java
  src/main/java/com/enderio/base/data/tags/EIOItemTagsProvider.java
Labels: Area-Backend, MC-1.20.1

#517 Switch to concurrent hashmap for tracking fire.
  src/main/java/com/enderio/base/common/handler/FireCraftingHandler.java
Labels: Type-Bug, Area-Mod Integration, Area-Backend, MC-1.20.1, P-0-High

#480 Small adjustment to the soul binding jei recipe
  src/machines/java/com/enderio/machines/common/integrations/jei/category/SoulBindingCategory.java
Labels: Type-Bug, Area-Mod Integration, Area-Backend, MC-1.20.1

#492 added filter for fluidTank fill and drain inputs
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
Labels: Type-Enhancement, MC-1.20.1
