Repository Team-EnderIO/EnderIO, pull requests merged in 2024-02, with the labels that each got.

#614 Publish to my maven after release build is successful.
  .github/workflows/release.yml
  build.gradle
Labels: Area-Backend

#615 Fix gear tag
  src/generated/resources/data/enderio/recipes/alloy_smelter.json
  src/generated/resources/data/enderio/recipes/crafter.json
  src/generated/resources/data/enderio/recipes/drain.json
  src/generated/resources/data/enderio/recipes/impulse_hopper.json
  src/generated/resources/data/enderio/recipes/painting_machine.json
  src/generated/resources/data/enderio/recipes/sag_mill.json
  src/generated/resources/data/enderio/recipes/stirling_generator.json
  src/generated/resources/data/forge/tags/items/gears.json
  src/generated/resources/data/forge/tags/items/gears/iron.json
  src/generated/resources/data/forge/tags/items/gears/stone.json
  src/main/java/com/enderio/base/common/tag/EIOTags.java
Labels: Area-Datapacks

#616 Prevent item duplication by updating processing recipes in SAG Mill
  src/generated/resources/data/enderio/recipes/sag_milling/bone_block.json
  src/generated/resources/data/enderio/recipes/sag_milling/ender_crystal.json
  src/generated/resources/data/enderio/recipes/sag_milling/ender_pearl.json
  src/generated/resources/data/enderio/recipes/sag_milling/glass.json
  src/generated/resources/data/enderio/recipes/sag_milling/glowstone.json
  src/generated/resources/data/enderio/recipes/sag_milling/gold.json
  src/generated/resources/data/enderio/recipes/sag_milling/iron.json
  src/generated/resources/data/enderio/recipes/sag_milling/lapis.json
  src/generated/resources/data/enderio/recipes/sag_milling/precient_crystal.json
  src/generated/resources/data/enderio/recipes/sag_milling/pulsating_crystal.json
  src/generated/resources/data/enderio/recipes/sag_milling/quartz.json
  src/generated/resources/data/enderio/recipes/sag_milling/quartz_block.json
  src/generated/resources/data/enderio/recipes/sag_milling/quartz_slabs.json
  src/generated/resources/data/enderio/recipes/sag_milling/quartz_stairs.json
  src/generated/resources/data/enderio/recipes/sag_milling/sandstone.json
  src/generated/resources/data/enderio/recipes/sag_milling/soularium.json
  src/generated/resources/data/enderio/recipes/sag_milling/stone.json
  src/generated/resources/data/enderio/recipes/sag_milling/vibrant_crystal.json
  src/generated/resources/data/enderio/recipes/sag_milling/wool.json
  src/machines/java/com/enderio/machines/common/blockentity/SagMillBlockEntity.java
  src/machines/java/com/enderio/machines/common/integrations/jei/category/SagMillCategory.java
  src/machines/java/com/enderio/machines/data/recipes/SagMillRecipeProvider.java
Labels: Type-Bug, MC-1.20.1, P-1-Medium

#561 Rework tank logic
  src/core/java/com/enderio/core/CoreNBTKeys.java
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceCraftingWidget.java
  src/machines/java/com/enderio/machines/client/gui/widget/ExperienceWidget.java
  src/machines/java/com/enderio/machines/client/gui/widget/FluidStackStaticWidget.java
  src/machines/java/com/enderio/machines/client/gui/widget/FluidStackWidget.java
  src/machines/java/com/enderio/machines/client/rendering/blockentity/FluidTankBER.java
  src/machines/java/com/enderio/machines/common/blockentity/DrainBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/FluidTankBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulBinderBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/SoulEngineBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPObeliskBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/XPVacuumBlockEntity.java
  src/machines/java/com/enderio/machines/common/blockentity/base/MachineBlockEntity.java
  src/machines/java/com/enderio/machines/common/io/fluid/IFluidItemInteractive.java
  src/machines/java/com/enderio/machines/common/io/fluid/MachineFluidHandler.java
  src/machines/java/com/enderio/machines/common/io/fluid/MachineFluidTank.java
  src/machines/java/com/enderio/machines/common/io/fluid/MachineTankLayout.java
  src/machines/java/com/enderio/machines/common/io/fluid/TankAccess.java
  src/machines/java/com/enderio/machines/common/recipe/TankRecipe.java
Labels: Type-Enhancement, MC-1.20.1, Area-Parity
