Repository Team-EnderIO/EnderIO, pull requests merged in 2024-07, with the labels that each got.

#707 Misc travel improvements
  src/api/java/com/enderio/api/travel/TravelRenderer.java
  src/machines/java/com/enderio/machines/client/rendering/travel/TravelAnchorRenderer.java
  src/main/java/com/enderio/base/client/travel/TravelTargetRendering.java
  src/main/java/com/enderio/base/common/handler/TravelHandler.java
Labels: Type-Enhancement, MC-1.21

#646 Port RefinedStorage conduits to 1.20.1 version
  build.gradle
  gradle.properties
  src/conduits/java/com/enderio/conduits/common/integrations/Integrations.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/RSConduitType.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/RSIntegration.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/RSNetworkNode.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/RSNodeHost.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/RSTicker.java
  src/conduits/java/com/enderio/conduits/common/integrations/refinedstorage/package-info.java
  src/conduits/java/com/enderio/conduits/common/tag/ConduitTags.java
  src/conduits/java/com/enderio/conduits/data/recipe/ConduitRecipes.java
  src/conduits/resources/assets/enderio/textures/block/conduit/refined_storage.png
  src/conduits/resources/assets/enderio/textures/conduit_icon/refined_storage.png
  src/conduits/resources/assets/enderio/textures/gui/conduit_icon.png
  src/generated/resources/assets/enderio/lang/en_ud.json
  src/generated/resources/assets/enderio/lang/en_us.json
  src/generated/resources/assets/enderio/models/item/refined_storage_conduit.json
  src/generated/resources/data/enderio/recipes/rs_cable.json
Labels: Type-Enhancement, MC-1.20.1, Area-Parity, Area-Conduits

#740 Simplify acquisition of grains of infinity.
  enderio-base/src/generated/resources/.cache/236c8b0b309e8bd6a547e70d1043c055ffaf986a
  enderio-base/src/generated/resources/.cache/c88e66c1fc1e3156e52b96535d56d8f91fbc45ee
  enderio-base/src/generated/resources/assets/enderio/lang/en_us.json
  enderio-base/src/generated/resources/data/enderio/loot_table/fire_crafting/bedrock_infinity.json
  enderio-base/src/generated/resources/data/enderio/loot_table/fire_crafting/deepslate_infinity.json
  enderio-base/src/generated/resources/data/enderio/recipe/fire_crafting/bedrock_infinity.json
  enderio-base/src/generated/resources/data/enderio/recipe/fire_crafting/deepslate_infinity.json
  enderio-base/src/main/java/com/enderio/base/common/handler/FireCraftingHandler.java
  enderio-base/src/main/java/com/enderio/base/common/handler/GrindingHandler.java
  enderio-base/src/main/java/com/enderio/base/common/integrations/jei/EnderIOJEI.java
  enderio-base/src/main/java/com/enderio/base/common/integrations/jei/category/FireCraftingCategory.java
  enderio-base/src/main/java/com/enderio/base/common/lang/EIOLang.java
  enderio-base/src/main/java/com/enderio/base/common/recipe/FireCraftingRecipe.java
  enderio-base/src/main/java/com/enderio/base/data/loot/FireCraftingLootProvider.java
  enderio-base/src/main/java/com/enderio/base/data/recipe/FireCraftingRecipeProvider.java
  enderio-machines/src/generated/resources/.cache/aad1e49dd2f870dac7e75ef548e2e44fa7d73e02
  enderio-machines/src/generated/resources/data/enderio/recipe/sag_milling/cobbled_deepslate.json
  enderio-machines/src/generated/resources/data/enderio/recipe/sag_milling/cobblestone.json
  enderio-machines/src/generated/resources/data/enderio/recipe/sag_milling/deepslate.json
  enderio-machines/src/generated/resources/data/enderio/recipe/sag_milling/mossy_cobblestone.json
  enderio-machines/src/main/java/com/enderio/machines/data/recipes/SagMillRecipeProvider.java
Labels: Type-Enhancement, MC-1.21

#747 ChunkBoundLookup for Obelisk Managers
  endercore/src/main/java/com/enderio/core/common/util/ChunkBoundLookup.java
  enderio-machines/src/main/java/com/enderio/machines/common/blockentity/AversionObeliskBlockEntity.java
  enderio-machines/src/main/java/com/enderio/machines/common/blockentity/InhibitorObeliskBlockEntity.java
  enderio-machines/src/main/java/com/enderio/machines/common/blockentity/RelocatorObeliskBlockEntity.java
  enderio-machines/src/main/java/com/enderio/machines/common/blockentity/base/ObeliskBlockEntity.java
  enderio-machines/src/main/java/com/enderio/machines/common/init/MachineAttachments.java
  enderio-machines/src/main/java/com/enderio/machines/common/obelisk/AversionObeliskManager.java
  enderio-machines/src/main/java/com/enderio/machines/common/obelisk/InhibitorObeliskManager.java
  enderio-machines/src/main/java/com/enderio/machines/common/obelisk/ObeliskAreaManager.java
  enderio-machines/src/main/java/com/enderio/machines/common/obelisk/RelocatorObeliskManager.java
  enderio-machines/src/main/java/com/enderio/machines/common/obelisk/package-info.java
Labels: Area-Backend, MC-1.21
