Repository Team-EnderIO/EnderIO, pull requests merged in 2024-03, with the labels that each got.

#635 Unlock Registrate version range, should fix mod compat issues
  build.gradle
  gradle.properties
Labels: Area-Backend, MC-1.20.1

#632 Experiment: Convert gradle to Kotlin
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  build.gradle
  build.gradle.kts
  gradle.properties
  settings.gradle
  settings.gradle.kts
  src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
Labels: Area-Backend

#637 Fix primitive alloy smelter slot funk
  .github/workflows/verify.yml
  src/machines/java/com/enderio/machines/common/utility/RecipeInputCache.java
Labels: Type-Bug, MC-1.20.4

#639 Fix fluid handler not properly filtering
  src/machines/java/com/enderio/machines/common/io/TransferUtil.java
  src/machines/java/com/enderio/machines/common/io/fluid/MachineFluidHandler.java
Labels: Type-Bug, Area-Backend, MC-1.20.4
