Repository Team-EnderIO/EnderIO, pull requests merged in 2025-03, with the labels that each got.

#1022 Update to Create 6
  build.gradle
  src/core/java/com/enderio/core/common/compat/FlywheelCompat.java
  src/main/resources/META-INF/mods.toml
Labels: Area-Backend, MC-1.20.1, Area-Conduits, P-0-High

#1007 fix: Port fix for loading large conduit networks from 1.20.1
  enderio-conduits/src/main/java/com/enderio/conduits/common/conduit/ConduitSavedData.java
Labels: Area-Conduits, P-0-High, MC-1.21.1

#1042 [BUG] Fix Version Requirements for Refined Storage
  gradle.properties
Labels: Type-Bug, Area-Conduits, MC-1.21.1
